TrajectoryPlannerROS:
  # Robot parameters
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  
  # Acceleration limits
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  
  # Goal tolerance
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  
  # Forward simulation parameters
  vx_samples: 6
  vtheta_samples: 20
  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  
  # Scoring parameters
  goal_distance_bias: 32.0
  path_distance_bias: 32.0
  occdist_scale: 0.1
  heading_lookahead: 0.325
  dwa: false
  heading_scoring: false
  
  # Oscillation prevention
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.1
  escape_reset_theta: 0.0