global_costmap:
  global_frame: robot1_map
  robot_base_frame: robot1_base_footprint
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: false
  rolling_window: false
  track_unknown_space: true
  
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}