move_base:
  global_costmap:
    global_frame: /map
    robot_base_frame: base_footprint
    update_frequency: 1.0
    publish_frequency: 0.5
    static_map: true
    resolution: 0.05
    origin_x: 0.0
    origin_y: 0.0
    
    plugins:
      - {name: static_layer, type: 'costmap_2d/StaticLayer'}
      - {name: obstacle_layer, type: 'costmap_2d/ObstacleLayer'}
      - {name: inflation_layer, type: 'costmap_2d/InflationLayer'}
    
    static_layer:
      map_topic: /map
      subscribe_to_updates: true
    
    obstacle_layer:
      observation_sources: laser_scan
      laser_scan: {sensor_frame: laser_link, data_type: LaserScan, topic: /limo/scan, marking: true, clearing: true}
      footprint_clearing_enabled: true
      max_obstacle_height: 2.0
      track_unknown_space: true
    
    inflation_layer:
      inflation_radius: 0.55
      cost_scaling_factor: 10.0