move_base:
  shutdown_costmaps: false
  controller_frequency: 10.0
  planner_patience: 5.0
  controller_patience: 15.0
  max_planning_retries: -1
  clearing_rotation_allowed: true
  recovery_behaviors:
    - name: 'conservative_reset'
      type: 'clear_costmap_recovery/ClearCostmapRecovery'
    - name: 'rotate_recovery'
      type: 'rotate_recovery/RotateRecovery'
  
  # Base frame and map frame
  global_costmap:
    global_frame: /map
    robot_base_frame: base_footprint
  
  local_costmap:
    global_frame: odom
    robot_base_frame: base_footprint