global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 0.5
  static_map: true
  track_unknown_space: true
  resolution: 0.05             # IMPORTANT: Check your map resolution!
  always_send_full_costmap: false 
  transform_tolerance: 0.5
  
  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}